### ISSUE TITLE
a Commodore 16 TAP which works with emulator, not with Tapuino

### ISSUE THREAD

**Issue by sblendorio** [sweetlilmre/tapuino#41]
Which parameters (TICKER RATE, etc...) should I change to make this TAP work?
https://www.dropbox.com/s/rifwscth1kie20y/C16VB12.zip?dl=0

For "doesn't work" I mean: it loads first prg, which is a turboloader, then loads the **second** program, which on emulator works, while on Tapuino raises **"?LOAD ERROR"**

I set MachineType=C16 PAL both on emulator and tapuino.

On emulator works, on tapuino it doesn't.

Thanks in advance

**Comment by sweetlilmre** [comment]
Hi @sblendorio 

This is highly likely due to a buffer under run (data cannot be loaded fast enough to meet the requirements of the turboloader).

You could try a faster SD card and see if there is any improvement, I have see this work with turboloaders before.

I am working on the next version of the Tapuino which has been tested to work with the fastest turboloaders I could find (on the C64). I'd be very interested in connecting with folks that could test on C16 hardware. Follow me on twitter (https://twitter.com/sweetlilmre) for more info.

**Comment by sweetlilmre** [comment]
Hi [@sblendorio](https://github.com/sblendorio) 

This is highly likely due to a buffer under run (data cannot be loaded fast enough to meet the requirements of the turboloader).

You could try a faster SD card and see if there is any improvement, I have see this work with turboloaders before.

I am working on the next version of the Tapuino which has been tested to work with the fastest turboloaders I could find (on the C64). I'd be very interested in connecting with folks that could test on C16 hardware. Follow me on twitter ([https://twitter.com/sweetlilmre](https://twitter.com/sweetlilmre)) for more info.

**Comment by sblendorio** [comment]
Thank you @sweetlilmre, I'm also wondering how to set optimal values for parameters as TICKER-RATE, which have defaults, but I don't know their meaning. Is there a guide about these settings?

Thanks in advance.

Meanwhile I will try a microSD with better performances.

**Comment by sweetlilmre** [comment]
Hi,

TickerRate is the speed at which the filename scrolls when it is longer than the display length.

You are right, I really should have written some form of user manual but I am now concentrating on the TapuinoNext, so I'll add a page for that.
