### ISSUE TITLE
6 buttons

### ISSUE THREAD

**Issue by Sven1973** [sweetlilmre/tapuino#6]
At this moment are only 4 buttons implemented in software. For using a original housing of 1531 it will be nice to implement 2 more buttons.
RECORD for switching/toggeling recordmodes
EJECT for toggeling directories (as example)

**Comment by juri74** [comment]
i would not add more buttons because there are already lot of tapuino players that would have to redo all work, i will add support for 6 buttons in a different manner:

2 buttons pushed togheter; example: play and stop pushed togheter will ats like a eject, unloading tape and put you on the root of sd card
play + forward acts like record.. so you can put more microswitches but mantaining the compatibility for 4 buttons layout.
one interesting function however would be PAUSE, since there are lot of tapes with multiple programs on it, in this way could be possible to pause the tape, reset c64, type load"" and finally unpause the tape to continue loading...
this could be implemented with the "select" button: pressing it during tape loading will put pause on, pressing again will put pause off.

**Comment by Sven1973** [comment]
yes, your solution with two Buttons pushed together sounds plausible.
And it would work for me too, just a question of wiring...
thats a good idea !

**Comment by sweetlilmre** [comment]
closed stale.
